sonar.projectKey=isurangithilakshanaguniyangodage_hd-pipeline-app
sonar.organization=isurangithilakshanaguniyangodage
sonar.projectName=HD Pipeline App

sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/__tests__/**,**/coverage/**,**/reports/**,node_modules/**
sonar.tests=__tests__

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=reports/junit.xml
